import { Projects } from '@/types';

export const projects: Projects[] = [
  {
    project: 'Biennale Ecoposs',
    title: 'Trophée Ecoposs Concours De Nouvelles',
    slug: 'ecoposs-concours-de-nouvelles',
    description: "Trophée Ecoposs Concours de nouvelles 2022. Réalisé en chêne massif imprimé, aux couleurs bleu et jaune, ce trophée symbolise l'innovation, l'écriture et l'avenir durable. Remis lors de la Biennale Ecoposs à Lille, il récompense les lauréats du concours littéraire « Bonnes nouvelles du futur ».",
    year: 2022,
    materials: ['Chêne massif', 'Médium', 'Contreplaqué bouleau 2mm', 'Vitrificateur 1919 by Mauler'],
    techniques: ['Impression UV', 'Laquage bombe', 'Découpe laser'],
    partenaires: ['Ecoposs'],
    technologies: [],
    imageProject: ['/projects/BIENNALE_ECOPOSS/trophees-ecoposs-concours-nouvelles-osons-leloge-du-futur.webp','/projects/BIENNALE_ECOPOSS/trophee-ecoposs-osons-leloge-concours-bleu.webp', '/projects/BIENNALE_ECOPOSS/trophee-ecoposs-osons-leloge-concours.webp'],
    imagePartner: '/projects/BIENNALE_ECOPOSS/logo-ecoposs-osons-eloge-du-futur.webp',
  },
  {
    project: 'Concours Court Métrage - Cpam Lille Douai',
    title: 'Trophée Cpam Lille-Douai',
    slug: 'cpam-lille-douai',
    description: "À l'occasion de la Journée mondiale de lutte contre le sida, la Cpam Lille-Douai a remis un trophée original en bois lors d'un concours de courts-métrages. Sculpté en forme de ruban de solidarité, symbole universel, il incarne engagement, prévention et créativité pour sensibiliser le public à la lutte contre le VIH.",
    year: 2024,
    materials: ['Chêne massif', 'Huile Osmo'],
    techniques: ['Raboteuse', 'Dégauchisseuse', 'Fraiseuse numérique', 'Impression UV', 'Gravure laser sur socle'],
    partenaires: ['Cpam Lille Douai'],
    technologies: [],
    imageProject: ['/projects/concours_court_metrage_CPAM/trophee-artistique-bois-grave-incrustation.webp', '/projects/concours_court_metrage_CPAM/zoom-trophee-design-bois-ruban-pellicule.webp'],
    imagePartner: '/projects/concours_court_metrage_CPAM/logo-cpam-lille-douai.webp',
  },
  {
    project: 'Les Formidables',
    title: 'Trophée Les Formidables',
    slug: 'les-formidables',
    description: "Les Formidables 16/30 ans récompensent l'engagement des jeunes en Hauts-de-France. Organisé avec La Voix du Nord, ce concours distingue des initiatives solidaires, culturelles et entrepreneuriales. Le trophées en bois, au design symbolisant une montée d'escaliers vers l'avenir, valorise créativité, audace et implication citoyenne des lauréats.",
    year: 2022,
    materials: ['Contreplaqué bouleau 9mm', 'Contreplaqué bouleau 12mm pour socle', 'Vitrificateur 1919 by Mauler'],
    techniques: ['Scie à chantourner', 'Impression UV', 'Gravure sur socle'],
    partenaires: ['La Voix Du Nord'],
    technologies: [],
    imageProject: ['/projects/LES_FORMIDABLES/ambiance-trophee-design-bois-formidables-nord-pas-de-calais.webp', '/projects/LES_FORMIDABLES/laureat-trophee-les-formidables-16-30-ans-2021.jpg.webp', '/projects/LES_FORMIDABLES/trophee-design-bois-formidables-nord-pas-de-calais.webp', '/projects/LES_FORMIDABLES/trophee-les-formidables-16-30-ans-2025-categorie-entrepreneurs.webp', '/projects/LES_FORMIDABLES/zoom-trophee-design-bois-formidables-nord-pas-de-calais.webp','/projects/LES_FORMIDABLES/atelier-fabrication-trophees-personnalises-formidables-2021.webp'],
    imagePartner: '/projects/LES_FORMIDABLES/logo-lavoixdunord.webp',
  },
  {
    project: 'Lmc 100 Ans De Vie Commune',
    title: 'Trophée Lmc 100 Ans',
    slug: 'lmc-100-ans',
    description: "Pour célébrer ses 100 ans de vie commune (1925-2025), Lmc a organisé un événement exceptionnel récompensant ses 100 meilleurs clients. Un trophées en bois au design épuré, personnalisable par gravure, a été remis à chaque lauréat. Symbole de fidélité et de partenariat durable, il incarne un siècle d'histoire, d'engagement et de confiance partagée entre Lmc et ses clients.",
    year: 2025,
    materials: ['Contreplaqué 9mm', 'Contreplaqué 12mm pour socle'],
    techniques: ['Fraiseuse numérique', 'Impression UV', 'Gravure laser'],
    partenaires: ['Lmc'],
    technologies: [],
    imageProject: ['/projects/LMC_100_ans_de_vie_commune/trophée-design-contreplaqué-gravure-impression.webp','/projects/LMC_100_ans_de_vie_commune/fabrication-trophees-100-ans-de-vie-commune-2025.webp', '/projects/LMC_100_ans_de_vie_commune/trophee-100-ans-de-vie-commune-2025-cote-jaune.jpg.webp', '/projects/LMC_100_ans_de_vie_commune/trophee-100-ans-de-vie-commune-2025-cote.webp', '/projects/LMC_100_ans_de_vie_commune/trophee-100-ans-de-vie-commune-2025-face-jaune.jpg.webp', '/projects/LMC_100_ans_de_vie_commune/trophee-100-ans-de-vie-commune-2025-face.jpg.webp'],
    imagePartner: '/projects/LMC_100_ans_de_vie_commune/logo-quincaillerie-lmc.webp',
  },
  {
    project: 'Mon Héros Local',
    title: 'Trophée Mon Héros Local',
    slug: 'mon-heros-local',
    description: "Le concours Mon Héros Local, organisé en partenariat avec le Cic Nord Ouest depuis 4 ans, met en lumière celles et ceux qui entreprennent et agissent positivement dans leur territoire. Les lauréats reçoivent un trophées en bois au design moderne, gravé et coloré, symbole d'ancrage local et d'innovation. Cet événement valorise l'impact économique, sociétal et environnemental des initiatives locales, et s'impose comme un rendez-vous incontournable en Hauts-de-France et Normandie.",
    year: 2025,
    materials: ['Chêne américain', 'Huile Osmo'],
    techniques: ['Raboteuse', 'Dégauchisseuse', 'Scie sur table', 'Ciseaux à bois', 'Gravure laser', 'Laquage bombe pour le chant'],
    partenaires: ['Cic Nord Ouest'],
    technologies: [],
  imageProject: ['/projects/mon_heros_local_CIC/prix-entrepreneurs-bois-mon-heros-local-2025.webp', '/projects/mon_heros_local_CIC/recompenses-bois-cic-nord-ouest-2025.webp', '/projects/mon_heros_local_CIC/trophee-bois-mon-heros-local-2025-cic-nord-ouest.webp', '/projects/mon_heros_local_CIC/trophees-bois-design-mon-heros-local-2024-normandie-seul.webp', '/projects/mon_heros_local_CIC/trophees-bois-design-mon-heros-local-2024-normandie.webp', '/projects/mon_heros_local_CIC/zoom-trophee-bois-grave-hauts-de-france-2025.webp'],
  imagePartner: '/projects/mon_heros_local_CIC/cic-nord-ouest-logo.webp',
    },

    {
      project: 'Energic',
      title: 'Trophée Energic',
      slug: 'energic',
      description: "Ces trophées en forme de totem, inspirés du logo d’Energic (entreprise lilloise spécialisée dans l’animation de challenges RSE), sont réalisés en bois avec un travail d’incrustation graphique unique. Depuis plus de 6 ans, je collabore avec Energic pour concevoir et produire ces récompenses originales, offertes aux participants et lauréats de leurs défis autour de l’écologie, de l’innovation et de la transition durable. Ces pièces symbolisent à la fois engagement collectif et esprit d’équipe.",
      year: 2025,
      materials: ['Contreplaqué bouleau 30mm'],
      techniques: ['Gravure laser', 'Découpe à la scie à chantourner', 'Fraiseuse numérique si grande série'],
      partenaires: ['Energic'],
      technologies: [],
  imageProject: [ '/projects/TOTEMS_ENERGIC/trophee-bois-totem-design-grave.webp', '/projects/TOTEMS_ENERGIC/trophee-bois-gravure-laser-forme-totem.jpg.webp', '/projects/TOTEMS_ENERGIC/trophees-bois-oiseau-totem.webp', '/projects/TOTEMS_ENERGIC/trophees-ecoresponsables-totem-bois.webp'],
  imagePartner: '/projects/TOTEMS_ENERGIC/energic-Logo-baseline.webp',
    },
    {
      project: 'Trophées Dfcg',
      title: 'Trophée Finance & Gestion Dfcg HDF',
      slug: 'finance-gestion-dfcg-hauts-de-france',
      description: "Les trophées Finance & Gestion Dfcg Hauts-de-France récompensent chaque année les dirigeants financiers qui innovent et s’engagent dans la performance durable. En partenariat avec le Cic, l’événement met en lumière les talents de la région. J’ai conçu le design il y a 3 ans et depuis ils me font confiance pour la réalisation : des pièces uniques en bois massif, au design élégant et contemporain, associant gravure et couleurs sobres. Ces récompenses incarnent professionnalisme, excellence et innovation, valeurs partagées par la Dfcg, le Cic et l’écosystème financier régional.",
      year: 2025,
      materials: ['Chêne de haute qualité', 'Inserts en bouleau 1mm'],
      techniques: ['Raboteuse', 'Dégauchisseuse', 'Fraiseuse numérique', 'Gravure laser', 'Éléments insérés découpés à la laser puis imprimés à l’UV'],
      partenaires: ['Dfcg', 'Cic Nord Ouest', 'Ey'],
      technologies: [],
  imageProject: ['/projects/TROPHEES_DFCG/trophee-dfcg-hauts-de-france-2023-prix-laureats.webp', '/projects/TROPHEES_DFCG/remise-trophee-dfcg-hauts-de-france-2025.webp', '/projects/TROPHEES_DFCG/trophee-dfcg-hauts-de-france-2025-prix-finance.webp', '/projects/TROPHEES_DFCG/trophees-bois-design-dfcg-hauts-de-france-2025.webp', '/projects/TROPHEES_DFCG/zoom-trophee-bois-design-dfcg-hauts-de-france-2023.webp'],
  imagePartner: '/projects/TROPHEES_DFCG/logo-dfcg.webp',
    },
        {
      project: 'Start Innovation',
      title: 'Trophée Start Innovation CIC Business Awards',
      slug: 'start-innovation-cic-business-awards',
      description: "Le concours Start Innovation CIC Business Awards, porté par le Cic Nord Ouest, met chaque année en lumière les start-ups et entreprises innovantes des Hauts-de-France et de Normandie. Les lauréats sont récompensés par un trophée unique en bois massif, au design moderne et durable. Gravés et colorés de flèches dynamiques symbolisant la croissance et l’élan entrepreneurial, ces trophées incarnent audace, innovation et ancrage territorial. Ce partenariat durable avec le Cic en fait un rendez-vous majeur de l’écosystème entrepreneurial régional.",
      year: 2024,
      materials: ['Chêne upcyclé', 'Huile Osmo', 'Bouleau 1 mm pour insert'],
      techniques: ['Raboteuse', 'Dégauchisseuse', 'Scie sur table', 'Gravure laser', 'Petits éléments insérés découpés à la laser puis imprimés à l’UV'],
      partenaires: ['Cic Nord Ouest'],
      technologies: [],
  imageProject: ['/projects/START_INNOVATION/trophees-start-innovation-cic-business-awards-2024.webp','/projects/START_INNOVATION/20221117_165354.webp', '/projects/START_INNOVATION/trophees-bois-design-start-innovation-2024.webp', '/projects/START_INNOVATION/trophees-start-innovation-cic-business-awards-2021-zoom.webp', '/projects/START_INNOVATION/trophees-start-innovation-cic-business-awards-2021.webp'],
  imagePartner: '/projects/START_INNOVATION/cic-nord-ouest-logo.webp',
    },
  ];